version: '3.6'

services:
  postgres:
    image: postgres:13
    container_name: ptbbsweb_postgres_local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
